apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-gateway
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
spec:
  type: LoadBalancer
  loadBalancerIP: 10.4.4.130
  selector:
    app.kubernetes.io/instance: nginx-gateway
  ports:
    - name: http-tcp
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https-tcp
      protocol: TCP
      port: 443
      targetPort: 443
    - name: http-udp
      protocol: UDP
      port: 80
      targetPort: 80
    - name: https-udp
      protocol: UDP
      port: 443
      targetPort: 443
