apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hosting-visoft-dev
spec:
  secretName: hosting-visoft-dev-tls
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - visoft.dev
  privateKey:
    algorithm: ECDSA
  dnsNames:
    - hosting.visoft.dev
  issuerRef:
    name: visoft-dev-http01
    kind: Issuer
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-production-gateway
spec:
  gatewayClassName: nginx-production
  listeners:
    - name: production-visoft-dev-https
      protocol: HTTPS
      port: 443
      hostname: hosting.visoft.dev
      tls:
        certificateRefs:
          - kind: Secret
            name: hosting-visoft-dev-tls
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-production-gateway
spec:
  type: LoadBalancer
  loadBalancerIP: 10.4.4.140
  selector:
    app.kubernetes.io/instance: nginx-production-gateway
  ports:
    - name: https-tcp
      protocol: TCP
      port: 443
      targetPort: 443
    - name: https-udp
      protocol: UDP
      port: 443
      targetPort: 443
