apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: visoft-dev-http01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: nginx-production-gateway
                namespace: nginx-production-gateway
                kind: Gateway
