apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-visoft-dev
spec:
  secretName: registry-visoft-dev-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - visoft.dev
  privateKey:
    algorithm: ECDSA
  dnsNames:
    - registry.visoft.dev
  issuerRef:
    name: visoft-dev-dns01
    kind: Issuer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: topolvm-provisioner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-registry
  labels:
    app.kubernetes.io/name: oci-registry
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: oci-registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oci-registry
    spec:
      containers:
        - name: oci-registry
          image: registry:2
          ports:
            - containerPort: 443
          volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
            - name: auth
              mountPath: /auth
              readOnly: true
            - name: data
              mountPath: /var/lib/registry
          env:
            - name: REGISTRY_HTTP_ADDR
              value: 0.0.0.0:443
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /certs/tls.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /certs/tls.key
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: Registry Realm
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
      volumes:
        - name: certs
          secret:
            secretName: registry-visoft-dev-tls
        - name: auth
          secret:
            secretName: htpasswd
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: v1
kind: Service
metadata:
  name: oci-registry
spec:
  type: LoadBalancer
  loadBalancerIP: 10.4.4.135
  selector:
    app.kubernetes.io/name: oci-registry
  ports:
    - name: https-tcp
      protocol: TCP
      port: 443
      targetPort: 443
    - name: https-udp
      protocol: UDP
      port: 443
      targetPort: 443
