---
- name: Setup Environment from .env file
  hosts: localhost

  tasks:
    - name: Load .env file
      shell: cat ../.env
      register: dotenv

    - name: Create dictionary from .env
      set_fact:
        env_vars: "{{ env_vars | default({}) | combine({item.split('=')[0]: item.split('=')[1]}) }}"
      loop: "{{ dotenv.stdout_lines }}"
      when: item | regex_search('^[\\w]+=[\\w]+')

    - name: Extract envs from env_vars
      set_fact:
        surrealdb_user: "{{ env_vars['SURREALDB_USER'] }}"
        surrealdb_pass: "{{ env_vars['SURREALDB_PASS'] }}"
        tikv_user: "{{ env_vars['TIKV_USER'] }}"
        tikv_pass: "{{ env_vars['TIKV_PASS'] }}"
        cloudflare_api_token: "{{ env_vars['CLOUDFLARE_API_TOKEN'] }}"

    - name: Set htpasswd
      set_fact:
        htpasswd: "{{ lookup('file', '../htpasswd') }}"
