---
- name: Setup OCI Distribution
  hosts: localhost

  tasks:
    - name: Create oci-registry namespace
      kubernetes.core.k8s:
        kind: Namespace
        name: oci-registry

    - name: Create Cloudflare API token secret
      kubernetes.core.k8s:
        name: cloudflare-api-token
        namespace: oci-registry
        definition:
          kind: Secret
          type: Opaque
          data:
            api-token: "{{ cloudflare_api_token | b64encode }}"

    - name: Create oci-registry secret
      kubernetes.core.k8s:
        name: htpasswd
        namespace: oci-registry
        definition:
          kind: Secret
          type: Opaque
          data:
            htpasswd: "{{ htpasswd | b64encode }}"

    - name: Create Cloudflare DNS01 Issuer
      kubernetes.core.k8s:
        namespace: oci-registry
        src: ../resources/issuer.yaml

    - name: Setup Docker OCI Distribution
      kubernetes.core.k8s:
        namespace: oci-registry
        src: ../resources/registry.yaml
