---
- name: Setup SurrealDB
  hosts: localhost

  tasks:
    - name: Install SurrealDB
      vars:
        surrealdb_user: "{{ env_vars['SURREALDB_USER'] }}"
        surrealdb_pass: "{{ env_vars['SURREALDB_PASS'] }}"
        tikv_user: "{{ env_vars['TIKV_USER'] }}"
        tikv_pass: "{{ env_vars['TIKV_PASS'] }}"
        path: "tikv://{{ tikv_user }}:{{ tikv_pass }}@tikv-pd:2379"
        credentials: "{{ {'path': path, 'initial_user': surrealdb_user, 'initial_pass': surrealdb_pass} }}"
        file_values: "{{ lookup('file', '../resources/values/surrealdb.yaml') | from_yaml }}"
        combined_values: "{{ file_values | combine({'surrealdb': credentials}, recursive=True) }}"
      kubernetes.core.helm:
        name: surrealdb
        namespace: tikv
        chart_ref: surrealdb
        chart_repo_url: https://helm.surrealdb.com
        atomic: true
        wait: true
        values: "{{ combined_values }}"
