---
- name: Setup TiKV
  hosts: localhost

  tasks:
    - name: Create TiDB Operator CRD
      kubernetes.core.k8s:
        src: https://raw.githubusercontent.com/pingcap/tidb-operator/v1.5.2/manifests/crd.yaml

    - name: Install TiDB Operator
      kubernetes.core.helm:
        name: tidb-operator
        namespace: tidb-admin
        chart_ref: tidb-operator
        chart_repo_url: https://charts.pingcap.org/
        atomic: true
        create_namespace: true
        wait: true
        values: "{{ lookup('file', '../resources/values/tidb-operator.yaml') | from_yaml }}"

    - name: Create TiKV namespace
      kubernetes.core.k8s:
        kind: Namespace
        name: tikv

    - name: Create TiKV secrets
      vars:
        secret_data: "{{ {tikv_user: tikv_pass | b64encode} }}"
      kubernetes.core.k8s:
        name: tidb-secret
        namespace: tikv
        definition:
          kind: Secret
          type: Opaque
          data: "{{ secret_data }}"

    - name: Install TiKV
      kubernetes.core.k8s:
        src: ../resources/tidb.yaml
